# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoistTaskAdder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableViewWithREST
  pod 'Alamofire', '~> 5.0.0-beta.7'
  pod 'PINRemoteImage', '3.0.3'
  pod 'Locksmith', '4.0'
  pod 'XLForm', '4.0'
  pod 'BRYXBanner', '0.8.4'

end
