package ca.todoist;

import java.util.ArrayList;
import java.util.List;

import ca.todoist.adder.ItemTask;
import ca.todoist.adder.Task;
import ca.todoist.adder.email.SendMail;

public class TodoistAdderForLists {

	public static void main(String[] args) {
		List<Task> links = getListOfLinks();
		new SendMail().sendTasks(links);
	}

	private static List<Task> getListOfLinks() {
		List<Task> tasks = new ArrayList<Task>();
		String category = "Mobile Certification";
		tasks.add(new ItemTask("1 - 1 - Overview of the Mobile Cloud Programming MOOC (9-34).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("1 - 2 - Overview of Content Providers and Content Resolvers (part 1) (12-31).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("1 - 3 - Overview of Content Providers and Content Resolvers (part 2) (8-35).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("1 - 4 - ContactsContentProviderSimple Example Walkthrough (26-36).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("2 - 1 - Overview of Content Providers and Content Resolvers (part 1 Q&A) (8-51).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("2 - 2 - Overview of Content Providers and Content Resolvers (part 2 Q&A) (5-05)).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 1 - Introduction (3-06).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 10 - Request Body Encoding (5-55).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 11 - HTTP Response Anatomy (5-36).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 12 - HTTP Response Codes (7-22).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 13 - Cookies (5-31).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 14 - Protocol Layering & HTTP Design Methodologies (6-39).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 15 - HTTP Polling (13-19).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 16 - REST (5-28).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 17 - Push Messaging (9-54).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 18 - Retrofit Client Code Walkthrough (12-39).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 19 - Introduction to Retrofit (13-35).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 2 - What are Communication Protocols- (4-14).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 3 -  Intro to HTTP (5-17).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 4 - Why HTTP- (4-11).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 5 - What is a Cloud Service- (7-45).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 6 -  HTTP Request Methods (4-45).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 7 - HTTP Request Anatomy (4-40).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 8 -  URLs & Query Parameters (8-45).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("3 - 9 -  Mime Types & Content Type Headers (7-54).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("4 - 1 -  What are Servlets- (4-23).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("4 - 2 -  A First Cloud Service with a Servlet (11-18).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("4 - 3 -  Request Routing and Web.xml (4-45).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("4 - 4 - Video Servlet Walkthrough (14-23).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("4 - 5 - Securely Handling Client Data & Avoiding Injection Attacks (8-26).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("4 - 6 -  Building Cloud Services on HTTP (9-38).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 1 - The Spring Dispatcher Servlet and Controller Abstraction (7-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 10 - Spring Controller Code Walkthrough (18-36).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 2 - Intro to Spring Controllers (4-51).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 3 - Accepting Client Data with RequestParam Annotations (5-40).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 4 - Accepting Client Data with PathVariable Annotations (4-54).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 5 - Accepting Client Data with Request Body Annotations & JSON (4-32).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 6 - Handling Multipart Data (9-45).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 7 - Generating Responses with the ResponseBody Annotation (6-48).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 8 - Custom Marshalling with Jackson Annotations (10-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("5 - 9 - Spring Boot & Application Structure (9-44).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("6 - 10 - Auto-scaling.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("6 - 11 - IaaS vs. PaaS.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("6 - 12 - Offloading to Cloud Provider Services.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("6 - 8 - Horizontal Scaling.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("6 - 9 - Load Balancing Stateless vs. Stateful Applications.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 1 - Spring Dependency Injection & Auto-wiring (12-32).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 10 - Spring Data REST Code Walkthrough.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 11 - Spring Data REST.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 2 - Spring Configuration Annotations (6-41).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 3 - Spring Dependency Injection Code Walkthrough (9-39).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 4 - Object to Database Mapping (5-17).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 5 - The Java Persistence API (9-58).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 6 - Spring Repositories.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 7 -  Understanding SQL Injection Attacks.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 8 - Spring Data Code Walkthrough.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("7 - 9 - Section 4 Module 1 Part 1- Sessions.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 1 - NoSQL Databases.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 10 - Google App Engine Code Walkthrough.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 11 - Google App Engine.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 2 -  Optimizing for Query Patterns.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 3 - Optimizing for Reads vs. Writes.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 4 -  Write Contention & Sharding.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 5 - Spring Data Mongo DB.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 6 - Amazon Dynamo DB.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 7 - Packaging Applications into WAR Files.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 8 - Deploying to Amazon Elastic Beanstalk.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("8 - 9 - Deploying to Google App Engine.mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 10 - Section 6 Module 3 Part 1- Patterns and Frameworks for Synchronous Event Handling, Connections, and Service Initialization (15-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 11 - Section 6 Module 3 Part 2- Patterns and Frameworks for Synchronous Event Handling, Connections, and Service Initialization (15-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 12 - Section 6 Module 3 Part 3- Patterns and Frameworks for Synchronous Event Handling, Connections, and Service Initialization (15-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 13 - Section 6 Module 3 Part 4- Patterns and Frameworks for Synchronous Event Handling, Connections, and Service Initialization (20-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 14 - Section 6 Module 4 Part 1- Patterns and Frameworks for Service Configuration and Activation (10-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 15 - Section 6 Module 4 Part 2- Patterns and Frameworks for Service Configuration and Activation (11-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 16 - Section 6 Module 4 Part 3- Patterns and Frameworks for Service Configuration and Activation (19-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 17 - Section 6 Module 4 Part 4- Patterns and Frameworks for Service Configuration and Activation (11-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 2 - Section 6 Module 1 Part 0- Applying Patterns and Frameworks to Concurrent and Networked Software (8-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 3 - Section 6 Module 1 Part 1- Overview of JAWS Web Server Case Study (9-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 4 - Section 6 Module 1 Part 2- Overview of JAWS Web Server Case Study (8-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 5 - Section 6 Module 1 Part 3- Overview of JAWS Web Server Case Study (10-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 6 - Section 6 Module 2 Part 1- Patterns and Frameworks for Service Access and Communication (10-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 7 - Section 6 Module 2 Part 2- Patterns and Frameworks for Service Access and Communication (7-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 8 - Section 6 Module 2 Part 3- Patterns and Frameworks for Service Access and Communication (10-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("9 - 9 - Section 6 Module 2 Part 4- Patterns and Frameworks for Service Access and Communication (7-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 1 - Section 6 Module 5 Part 1- Patterns and Frameworks for Concurrency and Synchronization (13-30) (1).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 1 - Section 6 Module 5 Part 1- Patterns and Frameworks for Concurrency and Synchronization (13-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 10 - Section 6 Module 6 Part 1- Patterns and Frameworks for Asynchronous Event Handling (11-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 11 - Section 6 Module 6 Part 2- Patterns and Frameworks for Asynchronous Event Handling (15-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 12 - Section 6 Module 6 Part 3- Patterns and Frameworks for Asynchronous Event Handling (12-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 13 - Section 6 Module 6 Part 4-  Patterns and Frameworks for Asynchronous Event Handling (10-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 14 - Section 6 Module 7 Part 1- Evaluating Patterns and Frameworks for Concurrent and Networked Software (26-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 2 - Section 6 Module 5 Part 2- Patterns and Frameworks for Concurrency and Synchronization (10-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 3 - Section 6 Module 5 Part 3- Patterns and Frameworks for Concurrency and Synchronization (7-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 4 - Section 6 Module 5 Part 4- Patterns and Frameworks for Concurrency and Synchronization (12-30).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 5 - Section 6 Module 5 Part 5-  Patterns and Frameworks for Concurrency and Synchronization (12-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 6 - Section 6 Module 5 Part 6- Patterns and Frameworks for Concurrency and Synchronization (13-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 7 - Section 6 Module 5 Part 7- Patterns and Frameworks for Concurrency and Synchronization (24-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 8 - Section 6 Module 5 Part 8- Patterns and Frameworks for Concurrency and Synchronization (12-00).mp4tasks.add(new ItemTask(", category));
		tasks.add(new ItemTask("10 - 9 - Section 6 Module 5 Part 9- Patterns and Frameworks for Concurrency and Synchronization (10-00).mp4tasks.add(new ItemTask(", category));
		return tasks;
	}
}
